import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { ConvexClientProvider } from "./_provider/ConvexClientProvider";

export const metadata: Metadata = {
  title: "CONSTRUX INTGRATION",
  description: "Generated by create next app",
  icons:'/img/icon.svg'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className="h-full antialiased"
      >
        <body className="min-h-full flex flex-col">
          <ConvexClientProvider>
          {children}
          </ConvexClientProvider>
          </body>
      </html>
    </ClerkProvider>
  );
}
